<?php
// $Id: openlayers_views.module,v 1.2.2.3 2009/08/20 23:21:55 binarybill Exp $

/**
 * @file
 * This file holds the main Drupal hook functions
 * and private functions for the openlayers_views module.
 *
 * @ingroup openlayers
 */

/**
 * Map ID Prefix
 */
define('OPENLAYERS_VIEWS_MAP_ID_PREFIX', 'openlayers-views-map-auto-id');

/**
 * Implementation of hook_help().
 */
function openlayers_views_help($path, $arg) {
  $output = '';

  switch ($path) {
    case 'admin/help#openlayers_views':
      $output = '<p>'. t('The OpenLayers Views module provides a set of plugins for Views.') .'</p>';
      return $output;

  }
}

/**
 * Implementation of hook_theme().
 */
function openlayers_views_theme($existing, $type, $theme, $path) {
  return array(
    'openlayers_views_feature_style' => array(
      'arguments' => array(
        'view' => NULL,
        'row' => NULL,
        'group' => NULL,
      ),
      'file' => 'includes/openlayers_views.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function openlayers_views_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'openlayers_views') .'/views',
  );
}
