<?php
// $Id: openlayers_views.theme.inc,v 1.1.2.2 2009/08/06 04:42:06 binarybill Exp $

/**
 * @file
 * This file holds the theme functions for openlayers_views module
 *
 * @ingroup openlayers
 */

/**
 * Theme function for openlayers_views_feature_style
 */
function theme_openlayers_views_feature_style($view = NULL, $row = NULL, $group = NULL) {
  $output = array();

  // Here is where styles based on the view or row can be created
  return $output;
}
