<?php
// $Id: gmap.views.inc,v 1.1.2.1 2010/11/30 22:08:55 bdragon Exp $

/**
 * @file
 * GMap views support.
 */

/**
 * Implementation of hook_views_handlers().
 */
/*
function gmap_views_handlers() {
  return array(
    'info' => array(
      'path' => drupal_get_path('module', 'gmap'),
    ),
    'handlers' => array(
      'gmap_plugin_style_gmap' => array(
        'parent' => 'views_plugin_style',
      ),
    ),
  );
}

*/
